#!/bin/sh

if [ "x$EDITOR" = "x" ]; then
    EDITOR=vi
fi

if [ $# != 1 ]; then
    echo "Usage: ./password <server>  --- prints out the entry containg the string server"
    echo "Usage: ./password --dump    --- prints the password file to stdout"
    echo "Usage: ./password --edit    --- edit the password file"
    echo "You will be prompted for the password"
    exit
fi

f=`gpg --decrypt passwords.txt.gpg`

if [ "$1" = "--dump" ]; then
    echo "$f"
elif [ "$1" = "--edit" ]; then
    echo "$f" > tmp
    $EDITOR tmp
    if [ $? = 0 ]; then
         gpg --symmetric --cipher-algo AES256 --output passwords.txt.gpg tmp
        if [ $? = 0 ]; then
            rm tmp
        fi
    fi
    if [ -f tmp ]; then
        echo "!!!!!!WARNING!!!!!! tmp STILL EXISTS AND CONTAINS PLAINTEXT PASSWORDS !!!!!!WARNING!!!!!!!"
    fi
else
    echo "$f" | awk -v server=$1 'BEGIN{RS=""} {if(tolower($0) ~ tolower(server)){print $0}}'
fi
