#!/bin/sh

if [ $# != 1 ]; then
    echo "Usage: ./password <server>  --- prints out the entry containg the string server"
    echo "Usage: ./password --dump  --- prints the password file to stdout"
    echo "You will be prompted for the password"
    exit
fi

f=`openssl bf-cfb -d -in passwords.txt.bf`

if [ "$1" = "--dump" ]; then
    echo "$f"
else
    echo "$f" | awk -v server=$1 'BEGIN{RS=""} {if($0 ~ server){print $0}}'
fi
