#!/bin/sh

# Polygonus
#
# Helps to manage a encrypted password file
#
# File should be of format
# section name
# info
# info
# ...
# <blank line>

if [ "x$EDITOR" = "x" ]; then
    EDITOR=vi
fi

if [ $# != 1 ]; then
    echo "Usage: ./password <string>  --- prints out the entry containg the string"
    echo "Usage: ./password --dump    --- prints the password file to stdout"
    echo "Usage: ./password --edit    --- edit the password file"
    echo "You will be prompted for the password"
    exit
fi

f=`gpg --decrypt passwords.txt.gpg`

if [ "$1" = "--dump" ]; then
    echo "$f"
elif [ "$1" = "--edit" ]; then
    echo "$f" > passwords.txt
    $EDITOR passwords.txt
    if [ $? = 0 ]; then
         gpg --symmetric --cipher-algo AES256 --output passwords.txt.gpg passwords.txt
        if [ $? = 0 ]; then
            rm passwords.txt
        fi
    fi
    if [ -f passwords.txt ]; then
        echo "!!!!!!WARNING!!!!!! passwords.txt STILL EXISTS AND CONTAINS PLAINTEXT PASSWORDS !!!!!!WARNING!!!!!!!"
    fi
else
    echo "$f" | awk -v server=$1 'BEGIN{RS=""} {if(tolower($0) ~ tolower(server)){print $0 "\n"}}'
fi
