#!/bin/bash

# Polygonus
#
# Helps to manage a encrypted password file
#
# File should be of format
# section name
# info
# info
# ...
# <blank line>

if [ "x$EDITOR" = "x" ]; then
    EDITOR=vi
fi

if [ $# != 2 ]; then
    echo "Usage: $0 <file> <string>  --- prints out the entry containg the string"
    echo "Usage: $0 <file> --dump    --- prints the password file to stdout"
    echo "Usage: $0 <file> --edit    --- edit the password file"
    echo "You will be prompted for the password"
    exit
fi

f=`gpg --decrypt $1`

if [ "$2" = "--dump" ]; then
    echo "$f"
elif [ "$2" = "--edit" ]; then
    tmpfile=$(tempfile)
    trap "rm $tmpfile" EXIT
    echo "$f" > $tmpfile
    $EDITOR $tmpfile
    if [ $? = 0 ]; then
         gpg --symmetric --cipher-algo AES256 --output $1 $tmpfile
    fi
    rm $tmpfile
else
    echo "$f" | awk -v server=$2 'BEGIN{RS=""} {if(tolower($0) ~ tolower(server)){print $0 "\n"}}'
fi
