#!/bin/bash

# Polygonus
#
# Helps to manage a encrypted password file
#
# File should be of format
# section name
# info
# info
# ...
# <blank line>

if [ "x$EDITOR" = "x" ]; then
    EDITOR=vi
fi

if [ $# != 1 ]; then
    echo "Usage: $0 <string>  --- prints out the entry containg the string"
    echo "Usage: $0 --dump    --- prints the password file to stdout"
    echo "Usage: $0 --edit    --- edit the password file"
    echo "You will be prompted for the password"
    exit
fi

f=`gpg --decrypt passwords.txt.gpg`

if [ "$1" = "--dump" ]; then
    echo "$f"
elif [ "$1" = "--edit" ]; then
    tmpfile=$(tempfile)
    trap "rm $tmpfile" EXIT
    echo "$f" > $tmpfile
    $EDITOR $tmpfile
    if [ $? = 0 ]; then
         gpg --symmetric --cipher-algo AES256 --output passwords.txt.gpg $tmpfile
    fi
    rm $tmpfile
else
    echo "$f" | awk -v server=$1 'BEGIN{RS=""} {if(tolower($0) ~ tolower(server)){print $0 "\n"}}'
fi
